USE BookingManagementDW
GO
DROP TABLE IF EXISTS dbo.AppointmentFT
DROP TABLE IF EXISTS dbo.Staff_memberDT

DROP TABLE IF EXISTS dbo.JunkDT


DROP TABLE IF EXISTS dbo.ProductDT
DROP TABLE IF EXISTS dbo.TimeDT
DROP TABLE IF EXISTS dbo.DateDT
DROP TABLE IF EXISTS dbo.ProcedureDT
DROP TABLE IF EXISTS dbo.ClientDT